site:
  title: StackRox Developer Docs Site
  # TODO: Change this
  url: "https://bradlugo.github.io/stackrox-dev-docs"
  start_page: stackrox::index.adoc
content:
  sources:
    - url: https://github.com/BradLugo/stackrox.git
      branches: docs
      start_path: docs
    - url: https://github.com/BradLugo/stackrox.git
      branches: docs
      start_path: docs/ui
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
